### ISSUE TITLE
Tools (page edit etc) should be more prominent

### ISSUE THREAD

**Issue by matthewandrews** [aruizca/jingo#13]
Right now the Tools button is really too small given its large role in the typical workflow in the wiki.  (It also gets completely hidden when the top bar wraps to two lines, but that's a different issue: #12 )

![screen shot 2016-02-04 at 9 54 55 am](https://cloud.githubusercontent.com/assets/611824/12799865/6aecd1ae-cb25-11e5-9e16-60c61aeaef8a.png)

A couple of options come to mind:
- add a Tools menu item into the top bar - perhaps just left of the username;
- move and expand Tools to become a block to the left of the page content (displaying each of the Tools items: create new page, edit this page, page history, all pages, search) - this would respond to narrow windows by becoming a horizontal list block between the nav bar and the page content;
- a more substantial change, moving the nav to a vertical block to the left of page content, and expanding the Tools items to occupy the top bar (a la Wikipedia UI).

Thoughts, @aruizca, @m-r-c?

**Comment by aruizca** [comment]
Not a fan of vertical menus TBH

**Comment by matthewandrews** [comment]
Another option I guess would be to adopt the Wikipedia approach - a series of horizontal tabs across the top of the page content: Edit this page, Page history, All pages, New page - we could drop search as it's already in the top bar.

**Comment by aruizca** [comment]
Not sure about tabs, but putting the available options at the top of the content pane might work:
![ala_wiki_ _home](https://cloud.githubusercontent.com/assets/246477/12800365/8517aeb6-cb28-11e5-9f7f-5568cb1ba265.png)

**Comment by matthewandrews** [comment]
Perhaps like this...

![new-tools-nav-tablike](https://cloud.githubusercontent.com/assets/611824/12800771/abec8cca-cb2b-11e5-89cf-abac58ba78a2.png)

**Comment by aruizca** [comment]
I was thinking more like a buttons toolbar. 
The way you are showing, you would need to cater for the delete action some other way and then maintain the current state to highlight it in the UI...I think

**Comment by matthewandrews** [comment]
Well it's a toolbar - each of the items is a link/button.

I imagine that during edit it would look like this - just a change in presentation look for the existing tools I think.
![jingo-new-tools-delete](https://cloud.githubusercontent.com/assets/611824/12801973/01c8df6e-cb35-11e5-85fe-7579980e7484.png)

**Comment by aruizca** [comment]
Then perhaps I would make them make look more like bootstrap buttons with
some little margin at the bottom and icons, because I honestly thought they
were tabs :-)

**Comment by matthewandrews** [comment]
Fair enough.  Here's another mockup of normal view...
![new-tools-buttons](https://cloud.githubusercontent.com/assets/611824/12803901/4a63abc0-cb42-11e5-935b-4dd66ea96856.png)
... and edit view:
![new-tools-delete-button](https://cloud.githubusercontent.com/assets/611824/12803906/556cf4c2-cb42-11e5-8bb5-7ac0d4b1a462.png)

**Comment by aruizca** [comment]
Looks good. Some icons would make it perfect :-) You have font-awesome icons set available BTW

**Comment by matthewandrews** [comment]
This is done now (on develop branch) and released to prod.
